### ISSUE TITLE
Github pages/live demo down

### ISSUE THREAD

**Issue by potatolain** [kevinselwyn/ReadNES.js#1]
Hey there! not sure if you're actively maintaining this anymore, but it seems like at some point the github pages version of this broke. Would it be possible to bring that back? It's quite useful to quickly split roms, and I'm not aware of any other web-based options. It looks like the `demo/` folder has everything in it. 

I tried both http://kevinselwyn.com/ReadNES.js/ and http://kevinselwyn.com/ReadNES. (The former is in the readme)

**Comment by kevinselwyn** [comment]
Thanks for calling this out! I've restored the page. Please let me know if you have any trouble with it. Thanks!

**Comment by potatolain** [comment]
Confirmed it's working for me, thanks so much!
